version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - cocacola
    ports:
      - 17027:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - cocacola

networks:
  cocacola:
    driver: bridge
